### ISSUE TITLE
No module Found error

### ISSUE THREAD

**Issue by Nithin745** [willmeyers/django-bunny-storage#2]
![Screenshot from 2022-04-16 17-24-51](https://user-images.githubusercontent.com/85417614/163673944-c85b97f0-d5e4-4971-aa85-d96c9a389ede.png)
![Screenshot from 2022-04-16 17-25-20](https://user-images.githubusercontent.com/85417614/163673952-8ba41d14-e415-446f-9df1-eafc91f3c7c3.png)
I getting this no module fond error

**Comment by willmeyers** [comment]
Thanks for raising this @Nithin745. I haven't done maintenance on this for a while now. I'll get this resolved most likely next week (just because of work, family, ...etc)

**Comment by Nithin745** [comment]
That's would be great, thanks for the quick reply.

**Comment by willmeyers** [comment]
Merged in fix in #3 @Nithin745 and published 0.1.2 to pip. Sorry about long wait, work is a bit hectic right now 😅

**Comment by Nithin745** [comment]
Thank you, for fixing the issue, It's working fine now.
